---
title: "Using densityarea"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using densityarea}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(densityarea)
library(dplyr)
library(tidyr)
library(purrr)
library(forcats)
library(sf)
library(ggplot2)
library(ggdensity)

data(s01)
```

```{r}
head(s01)
```

```{r}
s01 |> 
  ggplot(
    aes(
      x = F2,
      y = F1
    )
  )+
    stat_hdr(probs = 0.1)+
    scale_y_reverse()+
    scale_x_reverse()
```

```{r}
s01 |> 
  group_by(name) |> 
  summarise(
    polys = density_polygons(F2, F1, probs = c(0.1, 0.3, 0.5), as_st = T)
  ) |> 
  unnest(polys) 


```

```{r}
s01 |> 
  reframe(
    .by = plt_vclass,
    area = density_area(F1, F2, prob = 0.95),
    n = n()
  ) |> 
  tidyr::unnest(area) |> 
  mutate(
    plt_vclass = fct_reorder(plt_vclass, area)
  ) |> 
  ggplot(aes(plt_vclass, area))+
    geom_point(aes(size = n))
```
